on:
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: acc
        
        steps:
            
            - uses: actions/checkout@v4
            
            

            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t reehanruhullah/reehan:tagname .
                docker push reehanruhullah/reehan:tagname
                
                
            - name: run ansible playbook
              if: github.ref == 'refs/heads/master'
              env:
                password: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                ansible-playbook ansi.yml -i abc.txt --extra-vars "password=$password"